name: pull_requestイベントで発火するワークフロー

on:
  pull_request

jobs:
  call-hello:
    uses: ./.github/workflows/reuse.yml
    with:
      name: 'GitHub'
  check_pull_request_event_workflow:
    needs: call-hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World with pull request event"
      - name: Print time
        run: echo "Hello was said at ${{ needs.call-hello.outputs.time }}"