name: pull_requestイベントで発火するワークフロー

on:
  pull_request

jobs:
  call-hello:
    uses: ./.github/workflows/reusable-hello.yml
    with:
      name: 'GitHub'
  check_pull_request_event_workflow:
    needs: call-hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World with pull request event"