name: pushイベントで発火するワークフロー

on:
  push

jobs:
  reusable_workflow_job:
    uses: ./.github/workflows/reuse.yml
  check_push_event_workflow:
    strategy:
        matrix:
          job-number: [1, 2]  # 2つの並列ジョブ
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World with push event"
      - name: Check GITHUB_REF
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"