name: pushイベントで発火するワークフロー

on:
  push

jobs:
  check_push_event_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World with push event"
      - name: Check GITHUB_REF
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"