name: pushイベントで発火するワークフロー

on:
  push

jobs:
  call-hello:
    uses: ./.github/workflows/reuse.yml
    with:
      name: 'GitHub'
  check_push_event_workflow:
    needs: call-hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World with push event"